test20

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,6 +31,13 @@ jobs:
         run: |
           pytest --alluredir=allure-results || true
 
+      - name: Check if allure-results exists
+        run: |
+          if [ ! -d "allure-results" ] || [ -z "$(ls -A allure-results)" ]; then
+            echo "Allure results are empty or missing!"
+            exit 1
+          fi
+
       - name: Generate Allure HTML report
         uses: simple-elf/allure-report-action@v1.7
         with:
